### ISSUE TITLE
Allow for partial text searching

### ISSUE THREAD

**Issue by ihgann** [cbess/text-sherlock#38]
Currently, you can only search for nearly-exact string matches. For example, if I have a file with the string `veryLongString`, and I search `verylong`, it will show up as if there are no results. Only if I search for `veryLongString` will any results show up.

**Comment by cbess** [comment]
I believe this depends on the "searcher" you use, Xapian or Whoosh. Either way, you are able to use wildcards and operators, one of them should fix the problem. Try `veryLong*`

**Comment by ihgann** [comment]
Cool, thanks for the note!
