### ISSUE TITLE
Excluding directories?

### ISSUE THREAD

**Issue by sbrl** [cbess/text-sherlock#41]
I've got a bunch of git repositories, and I'd like to set up a code search engine to, well, search them. Text Sherlock looks like a good candidate, but unfortunately I can't figure out how to exclude the `.git` folder from the index - as it's slowing everything down and cluttering the search results.

**Comment by cbess** [comment]
Feature request?

**Comment by sbrl** [comment]
@cbess If it doesn't exist already, then yes this is a feature request :P

**Comment by cbess** [comment]
@sbrl `.git` (hidden) directories are now skipped by the indexer since v0.7.4
